SistemasGestionEmpresarial/1 Trimestre/Examen/Examen/Models/VM/vmConfirmarBorrado.cs
using Examen_Entidades;

namespace Examen_ASP.Models.VM
{
    public class vmConfirmarBorrado
    {
        #region Atributos
        private clsDepartamento departamento;
        private int numPersonasEnDept;
        private bool borrado;
        #endregion

        #region Propiedades
        public clsDepartamento Departamento { get { return departamento; } set { this.departamento = value; } }
        public int NumPersonasEnDept { get { return numPersonasEnDept; } set { this.numPersonasEnDept = value; } }
        public bool Borrado { get { return borrado; } set { this.borrado = value; } }
        #endregion

        #region Constructores
        public vmConfirmarBorrado() { }

        /// <summary>
        /// Construye el vm con el departamento pasado y obtiene el némero de personas en el departamento accediendo a la BBDD
        /// </summary>
        /// <param name="departamento"></param>
        public vmConfirmarBorrado(clsDepartamento departamento)
        {
            this.departamento = departamento;
            this.numPersonasEnDept = Examen_BL.Listados.clsListadosPersonasBL.obtenerPersonasDeDepartamentoBL(departamento.ID).Count();
            this.borrado = false;
        }


        #endregion
    }
}

SistemasGestionEmpresarial/1 Trimestre/Examen/Examen/Models/VM/vmListadoDepartamentos.cs
using Examen_Entidades;

namespace Examen_ASP.Models.VM
{
    public class vmListadoDepartamentos
    {
        #region Atributos
        private List<clsDepartamento> listadoDepartamentos;
        private List<clsPersona> listadoPersonas;
        #endregion

        #region Propiedades
        public List<clsDepartamento> ListadoDepartamentos { get { return listadoDepartamentos; } }
        public List<clsPersona> ListadoPersonas { get { return listadoPersonas; } }
        #endregion

        #region Constructores
        public vmListadoDepartamentos() {
            this.listadoDepartamentos = Examen_BL.Listados.clsListadosDepartamentosBL.obtenerListadoCompletoBL();
            this.listadoPersonas = Examen_BL.Listados.clsListadosPersonasBL.obtenerListadoCompletoBL();
        }

        #endregion
    }
}

SistemasGestionEmpresarial/1 Trimestre/Examen/Examen/Controllers/DepartamentosController.cs
using Examen_ASP.Models.VM;
using Examen_BL.Listados;
using Examen_Entidades;
using Microsoft.AspNetCore.Mvc;

namespace Examen_ASP.Controllers
{
    public class DepartamentosController : Controller
    {
        public IActionResult ListadoDepartamentos()
        {
            try
            {
                vmListadoDepartamentos vmListadoDepartamentos = new vmListadoDepartamentos();
                return View(vmListadoDepartamentos);
            }
            catch (Exception e)
            {
                ViewBag.Error = "Ha ocurrido un error, por favor inténtelo de nuevo más tarde.";
                return View(new vmListadoDepartamentos());
            }
        }

        public IActionResult ConfirmarBorrado(clsDepartamento departamento)
        {
            try
            {
                vmConfirmarBorrado vmConfirmarBorrado = new vmConfirmarBorrado(departamento);
                return View(vmConfirmarBorrado);
            }
            catch (Exception e)
            {
                ViewBag.Error = "Ha ocurrido un error ;(. Inténtelo de nuevo más tarde";
                return View(new vmConfirmarBorrado());
            }
        }
        [HttpPost]
        [ActionName("ConfirmarBorrado")]
        public IActionResult ConfirmarBorradoBorrar(clsDepartamento departamento)
        {
            vmConfirmarBorrado vmConfirmarBorrado = new vmConfirmarBorrado();
            try
            {
                List<clsPersona> personas = Examen_BL.Listados.clsListadosPersonasBL.obtenerPersonasDeDepartamentoBL(departamento.ID);
                int numPersonasEliminadas = 0;
                foreach (var persona in personas)
                {
                    if (Examen_BL.Manejadoras.clsManejadoraPersonaBL.eliminarPersonaBL(persona.ID) == 1)
                    {
                        numPersonasEliminadas++;
                    }
                }
                Examen_BL.Manejadoras.clsManejadoraDepartamentoBL.eliminarDepartamentoBL(departamento.ID);
                vmConfirmarBorrado.NumPersonasEnDept = numPersonasEliminadas;
                vmConfirmarBorrado.Departamento = departamento;
                vmConfirmarBorrado.Borrado = true;
                return View(vmConfirmarBorrado);
            }
            catch (Exception e)
            {
                ViewBag.Error = "Ha ocurrido un error ;(. Inténtelo de nuevo más tarde";
                return View(vmConfirmarBorrado);
            }
        }
    }
}

SistemasGestionEmpresarial/1 Trimestre/Examen/Examen/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Examen.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SistemasGestionEmpresarial/1 Trimestre/Examen/Examen/Views/Departamentos/ConfirmarBorrado.cshtml
@model Examen_ASP.Models.VM.vmConfirmarBorrado

@{
    ViewData["Title"] = "ConfirmarBorrado";
}

<title>Confirmar Borrado</title>
<h1>Confirmar Borrado</h1>


@if (ViewBag.Error == null)
{
    <hr />
    <h3>¿Está seguro de que desea borrar el departamento @Model.Departamento.Nombre?</h3>
    <hr />

    @if (Model.Borrado == false)
    {
        <p>Se eliminaran @Model.NumPersonasEnDept personas :O</p>
        <br />
        <form method="post">
            <input type="submit" value="Delete" class="btn btn-danger" />
        </form>
    }
    else
    {
        <p>Se ha eliminado el departamento y sus @Model.NumPersonasEnDept personas correctamente :)</p>
    }
}
else
{
    <hr />
    <p>@ViewBag.Error</p>
    <hr />
}

<br />
@Html.ActionLink("Volver", "ListadoDepartamentos", "Departamentos",new{}, new {style="border: 1px solid #000; padding: 5"})

SistemasGestionEmpresarial/1 Trimestre/Examen/Examen/Views/Departamentos/ListadoDepartamentos.cshtml
@model Examen_ASP.Models.VM.vmListadoDepartamentos

@{
    ViewData["Title"] = "ListadoDepartamentos";
}

<title>Listado Departamentos</title>
<br />
<h1>Listado Departamentos</h1>

<br />
<hr />

@if (@ViewBag.Error != null)
{
    <p>@ViewBag.Error</p>
}
else
{
    @if (Model.ListadoDepartamentos.Count > 0)
    {
        @foreach (var departamento in Model.ListadoDepartamentos)
        {
            <h1>@departamento.Nombre @Html.ActionLink("Borrar", "ConfirmarBorrado", "Departamentos", departamento, new {})</h1>

            @foreach (var persona in Model.ListadoPersonas)
            {
                @if (departamento.ID == persona.IDDepartamento)
                {
                    <ul>
                        <li>@persona.Nombre @persona.Apellidos, tlfn: @persona.Telefono</li>
                    </ul>
                }
            }
            <hr />
        }
    }
    else
    {
        <h2>No hay ningún departamento en la BBDD</h2>
    }
}